name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: make test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 8200b4a72cd17cd2ac8336dc82e9f132e6faa79215fe43a547c87d1674ad8e74
        with:
          coverageLocations: ${{github.workspace}}/cover.out:gocov
          prefix: /home/runner/work/atc-mid-cache-health-check

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./report.xml
          report_individual_runs: "true"